import subprocess, sys
from pathlib import Path
import json

BASE = Path(".").resolve()
SRC = BASE / "src"
TESTS = BASE / "tests"
TESTS.mkdir(exist_ok=True)

def sh(cmd, capture=False, check=True):
    print(f"$ {cmd}")
    result = subprocess.run(cmd, shell=True, text=True, capture_output=capture)
    if check and result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)
    return result.stdout if capture else ""

def get_changed_files():
    """
    Returns list of changed Python files between the PR branch and main.
    Works even on shallow clones or first-time PRs.
    """
    # Ensure we have the main branch locally
    subprocess.run(["git", "fetch", "origin", "main:refs/remotes/origin/main", "--depth=1"], check=False)
    # Try to find a merge base; fallback to all files if unavailable
    result = subprocess.run(
        ["git", "merge-base", "HEAD", "origin/main"],
        capture_output=True, text=True
    )
    base = result.stdout.strip()
    if not base:
        print("⚠️ No merge base found — probably first PR. Will consider all files in src/.")
        files = list(Path("src").rglob("*.py"))
    else:
        diff_output = subprocess.run(
            ["git", "diff", "--name-only", f"{base}...HEAD"],
            capture_output=True, text=True
        ).stdout.strip()
        files = [Path(line) for line in diff_output.splitlines() if line.endswith(".py")]
    # Filter for src files only
    files = [f for f in files if f.exists() and "tests" not in str(f) and str(f).startswith("src/")]
    print(f"📂 Changed files detected: {files}")
    return files


def generate_tests_with_copilot(file_path: Path):
    prompt = f"Write runnable pytest tests for {file_path}. Output only Python code."
    print(f"🧠 Asking Copilot for tests for: {file_path}")
    result = sh(f"gh copilot suggest --prompt {json.dumps(prompt)} --limit 1", capture=True)
    test_file = TESTS / f"test_{file_path.stem}.py"
    cleaned = result.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.replace("```python", "").replace("```", "")
    test_file.write_text(cleaned)
    print(f"✅ Generated {test_file}")
    return test_file

def run_pytest():
    print("🧪 Running pytest validation...")
    res = subprocess.run(["pytest", "-q", "--disable-warnings", "--maxfail=1"], text=True, capture_output=True)
    print(res.stdout)
    return res.returncode == 0

def git_commit_and_push(files):
    sh('git config user.name "ci-bot"')
    sh('git config user.email "ci-bot@users.noreply.github.com"')
    for f in files:
        sh(f"git add {f}")
    sh('git commit -m "auto: add pytest files generated by Copilot" || true', check=False)
    sh('git push', check=False)

def rollback(files):
    for f in files:
        if f.exists():
            f.unlink()
            print(f"🧹 Removed {f}")

if __name__ == "__main__":
    changed = get_changed_files()
    if not changed:
        print("ℹ️ No changed Python files.")
        sys.exit(0)

    generated = []
    for f in changed:
        generated.append(generate_tests_with_copilot(f))

    if run_pytest():
        print("✅ Tests passed! Committing and pushing.")
        git_commit_and_push(generated)
    else:
        print("❌ Tests failed. Rolling back generated tests.")
        rollback(generated)
        sys.exit(1)
import subprocess
from pathlib import Path
import sys

BASE = Path(".").resolve()
SRC = BASE / "src"
TESTS = BASE / "tests"
TESTS.mkdir(exist_ok=True)

def sh(cmd, capture=False, check=True):
    print(f"$ {cmd}")
    result = subprocess.run(cmd, shell=True, text=True, capture_output=capture)
    if check and result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        sys.exit(result.returncode)
    return result.stdout if capture else ""

def get_changed_files():
    out = sh("git fetch origin main && git diff --name-only origin/main...HEAD", capture=True)
    return [Path(line.strip()) for line in out.splitlines() if line.strip().endswith(".py")]

def generate_tests_with_copilot(file_path: Path):
    prompt = f"Write complete pytest test cases for {file_path}. Output only Python code."
    print(f"🧠 Asking Copilot for tests for {file_path}")
    result = sh(f"gh copilot suggest --prompt {json.dumps(prompt)} --limit 1", capture=True)
    test_path = TESTS / f"test_{file_path.stem}.py"
    test_path.write_text(result)
    print(f"✅ Generated: {test_path}")
    return test_path

def run_pytest():
    print("🧪 Running pytest validation...")
    res = subprocess.run(["pytest", "-q", "--disable-warnings", "--maxfail=1"], text=True, capture_output=True)
    print(res.stdout)
    return res.returncode == 0

def git_commit_and_push(files):
    sh('git config user.name "ci-bot"')
    sh('git config user.email "ci-bot@users.noreply.github.com"')
    for f in files:
        sh(f"git add {f}")
    sh('git commit -m "auto: add pytest files generated by Copilot" || true', check=False)
    sh('git push', check=False)

def rollback(files):
    for f in files:
        if f.exists():
            f.unlink()
            print(f"🧹 Removed {f}")

if __name__ == "__main__":
    changed = get_changed_files()
    if not changed:
        print("ℹ️ No changed Python files.")
        sys.exit(0)

    generated = []
    for f in changed:
        generated.append(generate_tests_with_copilot(f))

    if run_pytest():
        print("✅ Tests passed! Pushing to PR branch.")
        git_commit_and_push(generated)
    else:
        print("❌ Tests failed. Rolling back generated tests.")
        rollback(generated)
        sys.exit(1)
